# dotbot
# https://github.com/anishathalye/dotbot

- defaults:
    link:
      create: true
      relink: true
      glob: false
      force: false
    shell:
      quiet: true
      stdout: false
      stderr: true
    clean:
      force: false

- shell:
    - description: Setup alternatives (x-www-browser)
      command: test -f ~/.local/bin/x-www-browser || ln -sf /usr/bin/firefox ~/.local/bin/x-www-browser

    - description: Setup alternatives (www-browser)
      command: test -f ~/.local/bin/www-browser || ln -sf /usr/bin/firefox ~/.local/bin/www-browser

    - description: Setup alternatives (x-terminal-emulator)
      command: test -f ~/.local/bin/x-terminal-emulator || ln -sf "$(which kitty)" ~/.local/bin/x-terminal-emulator

    - description: Setup alternatives (x-window-manager)
      command: test -f ~/.local/bin/x-window-manager || ln -sf /usr/bin/i3 ~/.local/bin/x-window-manager

    - description: Setup xdg-terminal-exec (Overrides default terminal used by `glib/gio/gdesktopappinfo.c` which affects programs such as `gtk-launch` and `nautilus`)
      command: |
        # See: https://gitlab.gnome.org/GNOME/glib/-/blob/main/gio/gdesktopappinfo.c, known_terminals[] array. Glib uses a predefined set of terminals with precedence.
        # See: https://gitlab.freedesktop.org/xdg/xdg-specs/-/issues/54
        test -f ~/.local/bin/xdg-terminal-exec || ln -sf "$(which kitty)" ~/.local/bin/xdg-terminal-exec    # See: https://gitlab.gnome.org/GNOME/glib/-/commit/22e1b9bcc0ca7cd1ba2457ddf5b5545752f9c7ea
        test -f ~/.local/bin/rxvt || ln -sf "$(which kitty)" ~/.local/bin/rxvt

    - description: GNOME keyboard repeat rate / delay
      command: |
        gsettings set org.gnome.desktop.peripherals.keyboard repeat-interval 30
        gsettings set org.gnome.desktop.peripherals.keyboard delay 300

    - description: Gnome/Cinnamon gsettings setup preferred terminal
      stdout: false
      stderr: false
      command: |
        gsettings set org.gnome.desktop.default-applications.terminal exec kitty
        gsettings set org.gnome.desktop.default-applications.terminal exec-arg '--'
        gsettings set org.cinnamon.desktop.default-applications.terminal exec kitty
        gsettings set org.cinnamon.desktop.default-applications.terminal exec-arg '--'
        true

    - description: Dark mode for Gtk-4.0/Libadwaita apps
      command: gsettings set org.gnome.desktop.interface color-scheme prefer-dark

    - description: Install FZF
      stdout: false
      command: ./core/vendor/fzf/install --xdg --key-bindings --completion --no-update-rc

    - description: Install NVIM Python3 provider for neovim plugins (pynvim)
      command: pip3 install -U pynvim

    - description: Install NVIM NodeJS provider for neovim plugins (neovim)
      command: |
        npm install -g neovim
        npm update -g neovim

    - description: Give neovim a chance to download packer if not present
      stderr: false
      command: nvim --headless -c 'quitall!'

    - description: Refresh packer
      command: rm "$HOME/.config/nvim/plugin/packer_compiled.lua"; nvim --headless -c 'autocmd User PackerCompileDone quitall!' -c 'PackerCompile' 1> /dev/null 2> /dev/null

    - description: Install Neovim plugins
      stderr: false
      command: nvim --headless -c 'autocmd User PackerComplete quitall!' -c 'PackerSync'

    - description: Neovim Update remote plugins (technically deprecated)
      stderr: false
      command: nvim --headless -c 'UpdateRemotePlugins' -c qall

    - description: Update desktop database
      command: update-desktop-database ~/.local/share/applications

    - description: Refresh font cache
      command: fc-cache

    - description: Refresh X11 font cache
      command: |
        if command -v xset; then
          xset fp rehash
        fi

    - description: Refresh available user services
      command: systemctl --user daemon-reload

    - description: Enable user services
      command: |
        # systemctl --user enable .....

    - description: Clean pip cache
      command: command pip3 cache purge 2> /dev/null || true

    - description: Setup and sync between multiple programs config files GTK theming and Cursor theming
      command: |
        source "${USER_DOTFILES_LOCATION:-./}/meta/lib.sh"
        GTK_THEME=Adwaita-dark ICON_THEME=Adwaita CURSOR_THEME=Adwaita update_themes
      stdout: false
      stderr: false

    - description: Reload i3
      command: |
        if command -v i3-msg; then
          i3-msg reload || true
        fi
