# dotbot
# https://github.com/anishathalye/dotbot

- defaults:
    link:
      create: true
      relink: true
      glob: false
      force: false
    shell:
      quiet: true
      stdout: false
      stderr: true
    clean:
      force: false

- shell:
    - description: Install latest Kitty terminal
      command: |
        curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin launch=n
        ln -sf ~/.local/kitty.app/bin/kitty ~/.local/bin/
        cp -f ~/.local/kitty.app/share/applications/kitty.desktop ~/.local/share/applications/
        cp -f ~/.local/kitty.app/share/applications/kitty-open.desktop ~/.local/share/applications/
        sed -i "s|Icon=kitty|Icon=/home/$USER/.local/kitty.app/share/icons/hicolor/256x256/apps/kitty.png|g" ~/.local/share/applications/kitty*.desktop
        sed -i "s|Exec=kitty|Exec=/home/$USER/.local/kitty.app/bin/kitty|g" ~/.local/share/applications/kitty*.desktop

    - description: Setup alternatives (x-www-browser)
      command: test -f ~/.local/bin/x-www-browser || ln -sf /usr/bin/firefox ~/.local/bin/x-www-browser

    - description: Setup alternatives (www-browser)
      command: test -f ~/.local/bin/www-browser || ln -sf /usr/bin/firefox ~/.local/bin/www-browser

    - description: Setup alternatives (x-terminal-emulator)
      command: test -f ~/.local/bin/x-terminal-emulator || ln -sf "$(which kitty)" ~/.local/bin/x-terminal-emulator

    - description: Setup alternatives (x-window-manager)
      command: test -f ~/.local/bin/x-window-manager || ln -sf /usr/bin/i3 ~/.local/bin/x-window-manager

    - description: GNOME keyboard repeat rate / delay
      command: |
        gsettings set org.gnome.desktop.peripherals.keyboard repeat-interval 30
        gsettings set org.gnome.desktop.peripherals.keyboard delay 300

    - description: Gnome/Cinnamon gsettings setup preferred terminal
      stdout: false
      stderr: false
      command: |
        gsettings set org.gnome.desktop.default-applications.terminal exec kitty
        gsettings set org.gnome.desktop.default-applications.terminal exec-arg '--'
        gsettings set org.cinnamon.desktop.default-applications.terminal exec kitty
        gsettings set org.cinnamon.desktop.default-applications.terminal exec-arg '--'
        true

    - description: Dark mode for Gtk-4.0/Libadwaita apps
      command: gsettings set org.gnome.desktop.interface color-scheme prefer-dark

    - description: Install NVIM Python3 provider for remove plugins (pynvim)
      command: pip3 install -U pynvim

    - description: Install NVIM NodeJS provider for remove plugins (neovim)
      command: |
        npm install -g neovim
        npm update -g neovim

    - description: Give neovim a chance to download packer if not present
      stderr: false
      command: nvim --headless -c 'quitall!'

    - description: Refresh packer
      command: rm "$HOME/.config/nvim/plugin/packer_compiled.lua"; nvim --headless -c 'autocmd User PackerCompileDone quitall!' -c 'PackerCompile' 1> /dev/null 2> /dev/null

    - description: Install Neovim plugins
      stderr: false
      command: nvim --headless -c 'autocmd User PackerComplete quitall!' -c 'PackerSync'

    - description: Neovim Update remote plugins (technically deprecated)
      stderr: false
      command: nvim --headless -c 'UpdateRemotePlugins' -c qall

    - description: Update desktop database
      command: update-desktop-database ~/.local/share/applications

    - description: Refresh font cache
      command: fc-cache

    - description: Refresh X11 font cache
      command: |
        if command -v xset; then
          xset fp rehash
        fi

    - description: Refresh available user services
      command: systemctl --user daemon-reload

    - description: Enable user services
      command: |
        # systemctl --user enable .....

    - description: Clean pip cache
      command: command pip3 cache purge 2> /dev/null || true

    - description: Install FZF if not already installed
      command: which fzf || ./core/vendor/fzf/install --xdg --key-bindings --completion --no-update-rc

    - description: Setup and sync between multiple programs config files GTK theming and Cursor theming
      command: GTK_THEME=Adwaita-dark ICON_THEME=Adwaita CURSOR_THEME=Adwaita ./core/scripts/update.sh --themes
      stdout: false
      stderr: false

    - description: Reload i3
      command: |
        if command -v i3-msg; then
          i3-msg reload || true
        fi
