- defaults:
    link:
      create: true
      relink: true
      glob: false
      force: false
    shell:
      quiet: true
      stdout: false
      stderr: true
    clean:
      force: false

- shell:
    - description: Update to latest Kitty terminal
      stdout: false
      stderr: false
      command: |
        curl -L https://sw.kovidgoyal.net/kitty/installer.sh | sh /dev/stdin launch=n
        ln -sf ~/.local/kitty.app/bin/kitty ~/.local/bin/
        cp -f ~/.local/kitty.app/share/applications/kitty.desktop ~/.local/share/applications/
        cp -f ~/.local/kitty.app/share/applications/kitty-open.desktop ~/.local/share/applications/
        sed -i "s|Icon=kitty|Icon=/home/$USER/.local/kitty.app/share/icons/hicolor/256x256/apps/kitty.png|g" ~/.local/share/applications/kitty*.desktop
        sed -i "s|Exec=kitty|Exec=/home/$USER/.local/kitty.app/bin/kitty|g" ~/.local/share/applications/kitty*.desktop


    - description: Install NVIM lsp-servers, formatters, diagnostics tools
      stdout: false
      stderr: false
      command: |
        nvim --headless -c "MasonInstall stylua lua-language-server" -c "qall"
        nvim --headless -c "MasonInstall rust-analyzer texlab" -c "qall"
        nvim --headless -c "MasonInstall shellcheck shellharden" -c "qall"
