- defaults:
    link:
      create: true
      relink: true
      glob: false
      force: false
    shell:
      quiet: true
      stdout: false
      stderr: false
    clean:
      force: false

- description: Intel WIFI chipset, fix for bluetooth coexistence
  command: |
    # Fixes bluetooth headphone lags and reduced download link speed on WIFI connections
    # See here: https://wiki.archlinux.org/index.php/Network_configuration/Wireless#Bluetooth_coexistence
    #   and maybe also this: https://wiki.archlinux.org/index.php/Network_configuration/Wireless#iwlwifi
    #   and here: https://wireless.wiki.kernel.org/en/users/Drivers/iwlwifi#wi-fibluetooth_coexistence
    echo 'options iwlwifi bt_coex_active=0' | sudo tee -a /etc/modprobe.d/iwlwifi.conf

- description: Atheros WIFI chipset, fix for bluetooth coexistence
  command: |
    # See here: https://wiki.archlinux.org/title/bluetooth_headset#Connecting_works,_but_there_are_sound_glitches_all_the_time
    # Fixes slow wifi: https://wiki.archlinux.org/title/Network_configuration/Wireless#Atheros
    # NOTE: For  the PC the best approach is instead to disable
    #       bluetooth coexistence, and enable the antenna diversity
    #   - NOTE: From 24 December 2021:
    #               On the BM-350 motherboard with the Qualcomm Atheros AR93xx
    #               Wireless Network Adapter it seems that enabling the bt_ant_diversity leads
    #               to an unstable network connection.
    #               So the best approach seems to disable hardware encryption
    #               and disable Bluetooth_coexistence if possible (eg no need for bluetooth headsets)
    cat <<'EOF' | sudo tee /etc/modprobe.d/ath9k.conf
    options ath9k blink=0
    # Fix sound glitches and slow wifi when using bluetooth headphones
    # Enable wifi-BT coexistence
    options ath9k btcoex_enable=1
    # Disable hardware encryption (1 to disable)
    options ath9k nohwcrypt=0
    # Disable power saving
    options ath9k ps_enable=0
    # Disable WLAN/BT RX antenna diversity. Note that enabling antenna diversity may improve SNR,
    #  but requires that bluetooth coexistence is disabled (implies that "btcoex_enable" should be set to 0).
    #  If you do not care about bluetooth you can try to disable the above btcoex_enable option and enable
    #  the bt_ant_diversity=1 option
    options ath9k bt_ant_diversity=0
    EOF

- description: Remove SNAP and pin it so it can't be installed automatically again
  command: |
    if [ -x /usr/bin/snap ]; then
      sudo snap remove --purge snap-store
      sudo snap remove --purge 'gnome-*'
      sudo snap remove --purge core18
      sudo snap remove --purge snapd
      sudo umount /var/snap
      sudo apt purge -y snapd
      sudo apt-mark hold snapd
      rm -rf ~/snap
      sudo rm -rf /snap
      sudo rm -rf /var/snap
      sudo rm -rf /var/lib/snapd

      cat <<'EOF' | sudo tee /etc/apt/preferences.d/nosnap.pref
      # To prevent repository packages from triggering the installation of Snap,
      # this file forbids snapd from being installed by APT.
      # For more information: https://linuxmint-user-guide.readthedocs.io/en/latest/snap.html

      Package: snapd
      Pin: release a=*
      Pin-Priority: -10
      EOF
    fi
