---
- name: Install
  ansible.builtin.apt:
    name: zsh
    state: present
  become: true
  tags:
    - docker

- name: Setup ZDOTDIR to point to the user XDG config location
  ansible.builtin.lineinfile:
    path: /etc/zsh/zshenv
    line: export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
    regexp: "^export ZDOTDIR="
    create: true
  become: true
  tags:
    - zsh

- name: "Sets the user {{ lookup('env', 'USER') }} shell to zsh"
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    shell: /bin/zsh
  become: true
