#!/usr/bin/env bash
# -*- coding: utf-8 -*-

set -e

DOTFILES_LOCATION="${USER_DOTFILES_LOCATION:-$HOME/src/git/dparo/dotfiles}"

_invoke_dotbot() {
	DOTFILES_LOCATION="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
	cd "$DOTFILES_LOCATION" || exit 1

	DOTBOT_LOCATION="$DOTFILES_LOCATION/core/dotbot"
	DOTBOT_BIN="$DOTBOT_LOCATION/bin/dotbot"
	CONFIG="$DOTFILES_LOCATION/install.conf.yaml"

	# Update dot-files repo while avoiding merge conflicts
	update_dotbot_submodule() {
		git pull --ff-only
		git -C "$DOTBOT_LOCATION" submodule sync --quiet --recursive
		git submodule update --init --recursive --remote "$DOTBOT_LOCATION"
	}

	update_dotbot_submodule || true

	## Populate user HOME directory with these dotfiles using dotbot
	"$DOTBOT_BIN" --exit-on-failure -d "$DOTFILES_LOCATION" -c "$CONFIG" "$@"
	dotbot_result=$?

	if [ "$dotbot_result" -ne 0 ]; then
		echo "Dotbot failed with exit status $dotbot_result"
	fi

}

_bootstrap_prep_necessary_pkgs() {
	if [ -x /usr/bin/dnf ]; then
		# Core/Fundamental packages
		sudo dnf install -y util-linux-user python3-pyyaml p7zip p7zip-plugins sqlite
		sudo dnf install -y make cmake gcc g++ clang clang-tools-extra pip
		sudo dnf install -y nodejs npm tree-sitter-cli

		# Core command line tools
		sudo dnf install -y xclip ripgrep fd-find exa bat neovim tmux

		# Desktop stuff
		sudo dnf install -y i3 i3lock kitty feh nitrogen sxiv rofi dunst mpd mpc copyq

		sudo dnf remove 'libreoffice*'
		sudo dnf group remove libreoffice
	fi
}

_bootstrap_post_dotfiles_linked() {
	true
}

_bootstrap_dotfiles_repo() {
	if ! type git 1>/dev/null 2>/dev/null; then
		sudo dnf install -y git || sudo apt install -y git || sudo pacman -Syy git
	fi

	_bootstrap_prep_necessary_pkgs

	set -x

	if [ ! -d "$DOTFILES_LOCATION" ]; then
		mkdir -p "$(dirname "$DOTFILES_LOCATION")"
		git clone --depth 1 "https://github.com/dparo/dotfiles" "$DOTFILES_LOCATION"
	fi

	cd "$DOTFILES_LOCATION" || exit 1
	if [ "$USER" = "dparo" ]; then
		git remote set-url origin "git@github.com:dparo/dotfiles.git"
	fi

	set +x

	if ./install "$@"; then
		source "$HOME/.config/bash/bash_profile"
		source "$HOME/.config/bash/bashrc"
		_bootstrap_post_dotfiles_linked
	fi
}

main() {
	if test "$1" = "--bootstrap-dotfiles-repo"; then
		shift 1
		_bootstrap_dotfiles_repo "$@"
		return "$?"
	else
		_invoke_dotbot "$@"
		return "$?"
	fi
}

main "$@"
