---
- name: Install
  ansible.builtin.apt:
    name:
      - x11-xserver-utils
      - xsettingsd
      - xss-lock
      - xsecurelock
      - wmctrl
      - arandr
    state: present
  become: true
  tags:
    - xorg
    - apt


- name: Symlink config
  ansible.builtin.file:
    src: "{{ role_path }}/files"
    dest: "{{ ansible_user_dir }}/.config/xorg"
    state: link
  tags:
    - xorg
