---
- name: Install
  ansible.builtin.apt:
    name:
      - pipewire-pulse
      - pulseaudio-utils
      - pavucontrol
    state: present
  become: true
  tags:
    - pulseaudio
    - pipewire
    - apt
