---
- name: Install
  ansible.builtin.apt:
    name:
      - pipewire-pulse
      - pulseaudio-utils
      - pavucontrol
    state: present
  become: true
  tags:
    - pulseaudio
    - pipewire
    - apt


- name: Symlink config
  ansible.builtin.file:
    src: "{{ item }}"
    dest: "{{ ansible_user_dir }}/.config/pulse/{{ item | basename }}"
    state: link
  loop:
    - "{{ role_path }}/files/client.conf"
    - "{{ role_path }}/files/default.pa"
  tags:
    - pulseaudio
