---
- name: Install
  ansible.builtin.apt:
    pkg:
      - build-essential
      - gcc
      - g++
      - gdb
      - cmake
      - ninja-build
      - meson
      - clangd
      - clang-tidy
      - clang-tools
      - cppcheck
      - bear # Generate compilation database for clangtooling
      - valgrind
      - gperf
      - hyperfine
      # - flamegraph
      # - hotspot
      # - heaptrack
  become: true
  tags:
    - apt
    - cpp
    - gcc
