---
# List of additional commands that didn't make it:
# - coz-profiler: https://github.com/plasma-umass/coz
# - valgrind + kcachegrind
# - gperf
# - doxygen
# - flamegraph (cargo)   profiling tool
# - hyperfine (cargo)    benchmarking tool

- name: Install
  ansible.builtin.apt:
    name:
      - build-essential
      - gcc
      - g++
      - gdb
      - cmake
      - ninja-build
      - meson
      - clangd
      - clang-tidy
      - clang-tools
      - cppcheck
      - bear # Generate compilation database for clangtooling
      - valgrind
      - gperf
      - hyperfine
      # - flamegraph
      # - hotspot
      # - heaptrack
    state: present
  become: true
  tags:
    - apt
    - cpp
    - gcc
