---
- name: Install
  ansible.builtin.apt:
    name:
      - git
      - wget
      - curl
      - jq
      - rsync
      - p7zip-full
      - unrar
      - build-essential
      - python3-pip
      - bat
      - exa
      - tree
      - fd-find
      - htop
      - net-tools
      - lm-sensors
    state: present
  become: true
  tags:
    - core-pkgs
    - apt

- name: Symlink batcat
  ansible.builtin.file:
    src: /usr/bin/batcat
    dest: /usr/local/bin/bat
    state: link
  become: true
  tags:
    - core-pkgs
    - bat

- name: Symlink fdfind
  ansible.builtin.file:
    src: /usr/bin/fdfind
    dest: /usr/local/bin/fd
    state: link
  become: true
  tags:
    - core-pkgs
    - bat
