---
- name: Install
  ansible.builtin.apt:
    name:
      - nano
      - git
      - gnupg2
      - ca-certificates
      - openssh-client
      - polkitd
      - sqlite
      - wget
      - curl
      - jq
      - rsync
      - p7zip-full
      - unrar
      - unzip
      - atool # atool is a script for managing file archives of various types (tar,tar+gzip, zip etc)
      - build-essential
      - python3-pip
      - bat
      - exa
      - tree
      - fd-find
      - htop
      - btop
      - net-tools
      - lm-sensors
      - ffmpeg
    state: present
  become: true
  tags:
    - core-pkgs
    - apt

- name: Symlink batcat
  ansible.builtin.file:
    src: /usr/bin/batcat
    dest: /usr/local/bin/bat
    state: link
  become: true
  tags:
    - core-pkgs
    - bat

- name: Symlink fdfind
  ansible.builtin.file:
    src: /usr/bin/fdfind
    dest: /usr/local/bin/fd
    state: link
  become: true
  tags:
    - core-pkgs
    - bat
