---
- name: Install
  ansible.builtin.apt:
    name:
      - network-manager
      - openvpn
      - openvpn-systemd-resolved
      - openfortivpn
      - openconnect
      - network-manager-openvpn
      - network-manager-openconnect
    state: present
  become: true
  tags:
    - apt
    - network-manager
    - vpn
