---

- name: Install
  ansible.builtin.apt:
    pkg:
      - openjdk-11-jdk
      - openjdk-11-source
      - openjdk-18-jdk
      - openjdk-18-source
  become: true
  tags:
    - apt
    - java
    - jdk
    - openjdk
