---

# - name: Dependencies
#   ansible.builtin.package:
#     name:
#       - base-devel
#       - cmake
#       - curl
#       - ninja
#       - tree-sitter
#       - unzip
#     state: latest
#   become: true

- name: Clone
  ansible.builtin.git:
    clone: yes
    depth: 1
    dest: "{{ ansible_user_dir }}/opt/github.com/neovim/neovim"
    force: yes
    repo: https://github.com/neovim/neovim.git
    single_branch: yes
    update: yes
    version: "{{ neovim_version | default('master') }}"
  register: clone

- name: Build
  community.general.make:
    chdir: "{{ ansible_user_dir }}/opt/github.com/neovim/neovim"
    params:
      CMAKE_BUILD_TYPE: Release
  when: clone.changed

- name: Install
  community.general.make:
    chdir: "{{ ansible_user_dir }}/opt/github.com/neovim/neovim"
    target: install
  become: true
  when: clone.changed

- name: Remove build folder
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/opt/github.com/neovim/neovim/build"
    state: absent
  become: true

# - name: Config folder
#   ansible.builtin.file:
#     mode: "0755"
#     path: "{{ ansible_user_dir }}/.config/nvim"
#     state: directory
#
# - name: Copy init.lua
#   ansible.builtin.copy:
#     dest: "{{ ansible_user_dir }}/.config/nvim/init.lua"
#     src: "init.lua"
#
# - name: Copy modules
#   ansible.builtin.copy:
#     dest: "{{ ansible_user_dir }}/.config/nvim/lua"
#     src: "lua/"
