#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import readline
from math import *

import numpy as np

# Avoid writing ~/.python_history in HOME directory
readline.write_history_file = lambda *args: None
