---
- name: Create target dir
  ansible.builtin.file:
    path: "{{ maven_install_dir }}"
    state: directory
    mode: "0755"
  register: maven_target_dir
  tags:
    - maven


- name: Download and unpack
  ansible.builtin.unarchive:
    src: "https://dlcdn.apache.org/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz"
    dest: "{{ maven_install_dir }}"
    remote_src: yes
  when: maven_target_dir.changed
  tags:
    - maven

- name: Symlink maven binaries
  ansible.builtin.file:
    src: "{{ item }}"
    dest: "{{ ansible_user_home }}/.local/bin"
    state: link
  loop:
    - "{{ maven_install_dir }}/apache-maven-{{ maven_version }}/bin/mvn"
    - "{{ maven_install_dir }}/apache-maven-{{ maven_version }}/bin/mvnDebug"
    - "{{ maven_install_dir }}/apache-maven-{{ maven_version }}/bin/mvnyjp"
  tags:
    - maven
