---
- name: Disable services
  ansible.builtin.systemd:
    name: "{{item}}"
    enabled: false
  become: true
  when: ansible_env.RUNNING_INSIDE_DOCKER is undefined
  loop:
    - "gdm"
    - "gdm3"
  tags:
    - systemd
