---
- name: Install
  ansible.builtin.apt:
    name:
      - feh
      - nitrogen
      - scrot
      - flameshot
      - zathura
      - copyq
    state: present
  become: true
  tags:
    - apt
    - wm-basics
