---
- name: Install
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
    state: present
  become: true
  tags:
    - apt
    - python

- name: Clean PIP cache
  ansible.builtin.shell: |
    pip3 cache purge 2> /dev/null || true
  ignore_errors: true
  tags:
    - python
    - pip
