---
- name: Create swap file of {{ swapfile_size }} MiB
  ansible.builtin.shell: |
    set -e
    if ! test -f /swapfile && test {{ swapfile_size }} -gt 0; then
      dd if=/dev/zero of=/swapfile bs=1M count={{ swapfile_size }} status=progress
      chmod 0600 /swapfile
      mkswap -U clear /swapfile
      swapon /swapfile
    fi

    grep -qxE '/swapfile\s+none\s+swap\s+defaults\s+0\s+0' /etc/fstab || echo '/swapfile none swap defaults 0 0' >> /etc/fstab
  become: true
  when: ansible_env.RUNNING_INSIDE_DOCKER is undefined and ansible_env.RUNNING_INSIDE_VM is undefined and modify_filesystem
  tags:
    - swapfile
    - filesystem
