- name: Create items
  ansible.builtin.file:
    path: "{{item}}"
    state: directory
    mode: "0755"
  loop:
    - "{{ ansible_user_dir }}/Desktop"
    - "{{ ansible_user_dir }}/Downloads"
    - "{{ ansible_user_dir }}/Documents"
    - "{{ ansible_user_dir }}/Pictures"
    - "{{ ansible_user_dir }}/Music"
    - "{{ ansible_user_dir }}/Videos"
    - "{{ ansible_user_dir }}/.local/share/Templates"
    - "{{ ansible_user_dir }}/opt"
    - "{{ ansible_user_dir }}/.local/bin"
    - "{{ ansible_user_dir }}/.local/share/bin"
    - "{{ ansible_user_dir }}/.local/share/fonts"
    - "{{ ansible_user_dir }}/.local/share/sounds"
    - "{{ ansible_user_dir }}/.local/share/applications"
    - "{{ ansible_user_dir }}/.local/share/keyrings"
    - "{{ ansible_user_dir }}/.local/share/pki"
    - "{{ ansible_user_dir }}/.local/share/gnupg"
    - "{{ ansible_user_dir }}/.local/share/vscode"
    - "{{ ansible_user_dir }}/.cache"
    - "{{ ansible_user_dir }}/.cache/bash"
    - "{{ ansible_user_dir }}/.cache/zsh"
    - "{{ ansible_user_dir }}/.cache/mpd"
    - "{{ ansible_user_dir }}/.config"
    - "{{ ansible_user_dir }}/.config/systemd/user/default.target.wants"
    - "{{ ansible_user_dir }}/.ssh"
    - "{{ ansible_user_dir }}/.gnupg"
  tags:
    - xdg

- name: Delete items
  ansible.builtin.file:
    path: "{{item}}"
    state: absent
  loop:
    - "{{ ansible_user_dir }}/.bash_history"
    - "{{ ansible_user_dir }}/.bash_profile"
    - "{{ ansible_user_dir }}/.bashrc"
    - "{{ ansible_user_dir }}/.profile"
    - "{{ ansible_user_dir }}/.python_history"
    - "{{ ansible_user_dir }}/.lesshst"
    - "{{ ansible_user_dir }}/.sudo_as_admin_successful"
    - "{{ ansible_user_dir }}/Templates"
  tags:
    - xdg

- name: Remove broken symlinks in directories
  ansible.builtin.command: find -L "{{item}}" -maxdepth 1 -type l -delete
  loop:
    - "{{ ansible_user_dir }}"
    - "{{ ansible_user_dir }}/.config"
    - "{{ ansible_user_dir }}/.local/bin"
    - "{{ ansible_user_dir }}/.local/share/applications"
  tags:
    - xdg
