---
- name: Install
  ansible.builtin.apt:
    name:
      - adwaita-icon-theme-full
    state: present
  become: true
  tags:
    - apt
    - gtk
    - gtk-theme

- name: Symlink config
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - {
        src: "{{ role_path }}/files/gtk-2.0",
        dest: "{{ ansible_user_dir }}/.config/gtk-2.0",
      }
    - {
        src: "{{ role_path }}/files/gtk-3.0",
        dest: "{{ ansible_user_dir }}/.config/gtk-3.0",
      }
    - {
        src: "{{ role_path }}/files/gtk-4.0",
        dest: "{{ ansible_user_dir }}/.config/gtk-4.0",
      }
  tags:
    - gtk
    - gtk-theme

- name: Update x-cursor-theme alternatives
  ansible.builtin.lineinfile:
    path: /etc/alternatives/x-cursor-theme
    line: "Inherits=Adwaita"
    regexp: "^Inherits"
    create: true
  become: true
  tags:
    - gtk
    - gtk-theme
