---
- name: Install
  ansible.builtin.apt:
    name:
      - gnome-keyring
      - seahorse
    state: present
  become: true
  tags:
    - apt
    - gnome-keyring

- name: Enable keyring service
  ansible.builtin.systemd:
    name: gnome-keyring-daemon.service
    enabled: true
    scope: user
  tags:
    - keyring
  when: ansible_env.RUNNING_INSIDE_DOCKER is undefined

- name: Enable keyring socket
  ansible.builtin.systemd:
    name: gnome-keyring-daemon.socket
    enabled: true
    scope: user
  tags:
    - keyring
  when: ansible_env.RUNNING_INSIDE_DOCKER is undefined
