#!/bin/bash

if [ -f "$XDG_CONFIG_HOME/zsh/.zshenv" ]; then
	source "$XDG_CONFIG_HOME/zsh/.zshenv"
fi

[ -f "$XDG_CONFIG_HOME/zsh/.zprofile" ] && source "$XDG_CONFIG_HOME/zsh/.zprofile"
[ -f "$XDG_CONFIG_HOME/zsh/.zlogin" ] && source "$XDG_CONFIG_HOME/zsh/.zlogin"
