---
- name: Install
  ansible.builtin.apt:
    pkg:
      - git
      - wget
      - curl
      - p7zip-full
      - build-essential
      - python3-pip
      - bat
      - exa
      - firefox
  become: true
  tags:
    - core-pkgs
    - apt


- name: Symlink batcat
  ansible.builtin.file:
    src: /usr/bin/batcat
    dest: /usr/local/bin/bat
    state: link
  become: true
  tags:
    - core-pkgs
    - bat
