---
- name: Install
  ansible.builtin.apt:
    pkg:
      - x11-xserver-utils
      - xsettingsd
      - xss-lock
      - xsecurelock
      - wmctrl
      - arandr
  become: true
  tags:
    - x11
    - apt
