---
- name: Install git
  ansible.builtin.apt:
    name: git
    state: present
  become: true
  tags:
    - apt
    - git

- name: Check latest git-delta
  ansible.builtin.uri:
    url: https://api.github.com/repos/dandavison/delta/releases/latest
    return_content: true
  register: gitdelta_latest
  tags:
    - apt
    - git
    - git-delta

- name: Print return information from the previous task
  ansible.builtin.debug:
    var: gitdelta_latest
    verbosity: 2
  tags:
    - apt
    - git
    - git-delta

- name: Install latest git-delta
  ansible.builtin.apt:
    deb: "https://github.com/dandavison/delta/releases/download/{{ gitdelta_latest['json']['tag_name'] }}/git-delta_{{ gitdelta_latest['json']['tag_name'] }}_amd64.deb"
  tags:
    - apt
    - git
    - git-delta
