---

- name: Create target dir
  ansible.builtin.file:
    path:  "{{ maven_install_dir }}"
    state: directory
    mode: '0755'

- name: Download
  ansible.builtin.unarchive:
    src: "https://dlcdn.apache.org/maven/maven-3/{{ maven_version }}/binaries/apache-maven-{{ maven_version }}-bin.tar.gz"
    dest: "{{ maven_install_dir }}"
    remote_src: yes
