---
- name: Install
  ansible.builtin.apt:
    name:
      - blueman # A full featured Graphical Bluetooth Manager
      - bluez-tools # Set of tools to manage Bluetooth devices for linux
    state: present
  become: true
  tags:
    - apt
    - bluetooth
