---
- name: Install
  ansible.builtin.apt:
    name: docker.io
    state: present
  become: true
  tags:
    - docker

- name: Enable service
  ansible.builtin.systemd:
    name: docker
    enabled: false
  become: true
  tags:
    - docker


- name: "Add the user {{ lookup('env', 'USER') }} to the docker group"
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    group: docker
  become: true
