#!/usr/bin/env bash

set -x
set -e

source /etc/os-release

if ! test -x "$(command -v ansible)"; then
    case $ID in
    ubuntu)
        sudo apt update
        sudo apt install -y git ansible
        ;;

    arch)
        sudo pacman -S --noconfirm git ansible
        ;;
    esac
fi

DOTFILES_LOCATION="${XDG_DATA_HOME:-$HOME/.local/share}/dotfiles"
if ! test -d "$DOTFILES_LOCATION"; then
    mkdir -p "$DOTFILES_LOCATION"
    git clone --recursive "https://github.com/dparo/dotfiles" "$DOTFILES_LOCATION"
fi

pushd "$DOTFILES_LOCATION" || exit 1
exec ./ansible/install "$@"
