#!/usr/bin/env bash

cd "$(dirname "$0")" || exit

# ansible-galaxy install -r requirements.yml && \
    exec ansible-playbook --diff --extra-vars "@$PWD/values.yml" --ask-become-pass "$PWD/site.yml" "$@"
