#!/usr/bin/env bash

cd "$(dirname "$0")" || exit

export ANSIBLE_HOME="${XDG_DATA_HOME:-$HOME/.local/share}/ansible"
export ANSIBLE_GALAXY_CACHE_DIR="$GALAXY_CACHE_DIR"
export ANSIBLE_LOCAL_TEMP="$ANSIBLE_HOME/tmp"

if [[ -f "$PWD/requirements.yml" ]]; then
    # ansible-galaxy install -r "$PWD/requirements.yml"
    true
fi

exec ansible-playbook --diff --extra-vars "@$PWD/values.yml" --ask-become-pass "$PWD/site.yml" "$@"
