#!/usr/bin/env bash

cd "$(dirname "$0")" || exit

if [[ -f "$PWD/requirements.yml" ]]; then
    # ansible-galaxy install -r "$PWD/requirements.yml"
    true
fi

exec ansible-playbook --diff --extra-vars "@$PWD/values.yml" --ask-become-pass "$PWD/site.yml" "$@"
