---
- name: Install
  ansible.builtin.apt:
    name:
      - pipewire
      - wireplumber
    state: present
  become: true
  tags:
    - pipewire
    - wireplumber
    - apt

- name: Enable pipewire user service
  ansible.builtin.systemd:
    name: pipewire
    enabled: true
    scope: user
  tags:
    - pipewire
  when: not running_inside_docker

- name: Enable wireplumber user service
  ansible.builtin.systemd:
    name: wireplumber
    enabled: true
    scope: user
  tags:
    - pipewire
    - wireplumber
  when: not running_inside_docker

- name: Restart pipewire service
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: pipewire
    scope: user
  tags:
    - pipewire
  when: not running_inside_docker

- name: Restart wireplumber service
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: wireplumber
    scope: user
  tags:
    - pipewire
    - wireplumber
  when: not running_inside_docker
