---

- name: Import gpg private key
  ansible.builtin.shell:
    cmd: gpg --batch --passphrase {{ gpg_passphrase }} --pinentry-mode loopback --import
    stdin: "{{ gpg_private_key }}"
  ignore_errors: true
  no_log: true
  when: ansible_env.RUNNING_INSIDE_DOCKER is undefined
  tags:
    - gpg
