#! /bin/sh

cd "$HOME" || exit 1

bspc config automatic_scheme longest_side

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

# mod1 is alt, mod4 is super (windows key)
bspc config pointer_modifier mod1

bspc config border_width 1
bspc config window_gap 16
bspc config top_padding 0
bspc config bottom_padding 0

# I would like this to be set to true. But the floating resize sucks dicks if this is enabled.
bspc config honor_size_hints true

bspc config ignore_ewmh_focus false
bspc config ignore_ewmh_fullscreen none
bspc config ignore_ewmh_struts false

bspc config click_to_focus button1
bspc config focus_follows_pointer true
bspc config swallow_first_click true

bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a URxvt:fzf-float state=floating
bspc rule -a URxvt:float state=floating
bspc rule -a URxvt:Fuzzy state=floating
#bspc rule -a URxvt:calc state=floating

bspc rule -a Zathura state=tiled
bspc rule -a TelegramDesktop state=floating
bspc rule -a Emacs state=tiled
#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Chromium desktop='^2'
#bspc config focused_border_color \#ff0000
#bspc config normal_border_color \#980c0c

bspc config active_border_color "#ff00ff"
bspc config focused_border_color "#ff00ff"
bspc config normal_border_color "#8b008b"

xrdb -load "$HOME/.config/X11/.Xresources"
pgrep -U "$(whoami)" sxhkd || sxhkd 1>"$HOME/.config/sxhkd/stdoutlog.txt" 2>"$HOME/.config/sxhkd/stderrlog.txt" &

systemd-inhibit --what=handle-power-key sleep infinity &

systemctl --user restart dunst
systemctl --user restart mpd-notification

"$HOME/.config/X11/setup_background.sh" &

##
## Polybar
##
# Terminate already running bar instances
killall -q polybar
# Wait until the processes have been shut down
while pgrep -u "$USER" -x polybar >/dev/null; do sleep 1; done
polybar --reload main &

##
## Startup the programs (wait one second so that polybar and the notification daemon has enough time to startup)
##
sleep 1

copyq &
flameshot &
~/Software/Telegram/Telegram -startintray &
~/.dropbox-dist/dropboxd &
